### ISSUE TITLE
Quick Replies for Chat Plugin

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#1004]
Text + Suggestions (buttons) currently don’t create buttons in neither the chat plugin nor messaging UI.

As an example, it would be a good idea render a button below “some text” here:
![screenshot_2021-02-16_at_18 14 54](https://user-images.githubusercontent.com/74183162/108103158-d0bfe700-7089-11eb-90aa-96233d50c8ad.png)

### Suggestion Requirements

- A row of suggested replies that appear as a row of suggestion chips following the associated message. Maximum 13 suggestions, with a maximum of 25 characters each.

- The chips only display when the associated message is the most recent message within the conversation (including both system user and contact messages). The contact can tap a suggested reply to send the text reply to the system user.

- The chips will disappear when one has been clicked, so it is an ephemeral element of a conversation.

- These suggestions (buttons) should be displayed horizontally below the plain text that prompts them.

**Note**: Chips are compact elements that represent an input, attribute, or action. Chips allow users to enter information, make selections, filter content, or trigger actions.

### Inspiration:
![image](https://user-images.githubusercontent.com/6797037/112467416-4f820100-8d67-11eb-8bc2-8931ac072b84.png)

### Payload
```
{
   "conversation_id": "<CONVERSATION_ID>",
   "message": {
       "text": "Pick a color:",
       "quick_replies":[
          {
           "content_type":"text",
           "title":"Red",
           "payload":"<POSTBACK_PAYLOAD>"
          },{
           "content_type":"text",
           "title":"Green",
           "payload":"<POSTBACK_PAYLOAD>"
          }    
       ]
   }
}
```

**Comment by lucapette** [comment]
this is currently not supported by the live chat plugin and it's unclear if this is a request to support the feature (it reads more like a bug report... so I'm just trying to clarify)

**Comment by lizhutter** [comment]
if I'm not mistaken, @steffh and I discussed it as a feature similar to what facebook calls "quick replies" - so plain text with a button below it... I think it fits more as a request to support the feature; that was a mistake on my end!

**Comment by steffh** [comment]
this seems to be a duplicate to this ticket https://github.com/airyhq/airy/issues/862 and be also part of that ticket: https://github.com/airyhq/airy/issues/1072

i think we can close it as this is already being worked on.

**Comment by AitorAlgorta** [comment]
it will get rendered in both since the work is done in the lib

**Comment by lucapette** [comment]
@steffh how can it be a duplicate if we're talking about different sources? The ability to render structured data is source dependent so, say you want to render "suggestions from google" like we did in #862 for the chat plugin as a source (basically using their payloads in our own source), we have to implement the feature.

I believe the source of confusion here is around the fact we add rendering capabilities to core via a TypeScript library. While that's true, it doesn't solve the problem that each source *must* have their own definitions/ability to render specific payloads. The library solves a different problem (which is only organizational so to speak), it's because we'd have to duplicate the code of the rendering for the chat plugin both in the plugin itself and in the UI.

So if this is the problem, then this is not a duplicate nor a bug report. It's "multiple features" requests in one ticket (which is totally understandable)

**Comment by steffh** [comment]
@lucapette okay, got it. if that's the case, we maybe just need to change the title of this ticket here because it currently doesn't say "chat plugin" as the source it is related to.

i just was under the impression we use the same code, because we follow the google standard in the payload, but as i can see you seem to duplicate that and treat it per source even if you copy code, but that's most likely a smart choice as sources can indeed take different directions.

**Comment by lizhutter** [comment]
### Suggestion Requirements

- A row of suggested replies that appear as a row of suggestion chips following the associated message. Maximum 13 suggestions, with a maximum of 25 characters each.

- The chips only display when the associated message is the most recent message within the conversation (including both system user and contact messages). The contact can tap a suggested reply to send the text reply to the system user.

- The chips will disappear when one has been clicked, so it is an ephemeral element of a conversation.

- These suggestions (buttons) should be displayed horizontally below the plain text that prompts them.

**Note**: Chips are compact elements that represent an input, attribute, or action. Chips allow users to enter information, make selections, filter content, or trigger actions.

**Comment by bitboxer** [comment]
Sorry, but from reading this I am still not clear where the data is coming from that will be displayed here.

**Comment by AitorAlgorta** [comment]
Since this is in the `chatplugin` source we define the data we want to send, like we do with the RichCards. We can follow the same payload structure as the RichCards, and adapt it.
