### ISSUE TITLE
Primary use case: deflection as the main mode

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#1054]
Currently, the first message received from the contact in the chat plugin must be typed.

Instead of this route, we want the first interaction done by the contact to be via rich card or quick replies/suggestions (buttons).

Questions to think about:
- where can a system user define that?
- how can we further customize it?

**Comment by lucapette** [comment]
right now the welcome message (that's how we call it internally I think) is hard-coded and I think it's more than reasonable to provide users with an option to over-ride this via initialization options (so I mean in the snippet of code that actually renders the chat plugin).

I wonder if we should also have a more opinionated approach for the default: maybe a text message is not the best default and we can provide a slightly nicer default? (I can't think of anything right now though)

**Comment by steffh** [comment]
Fully agree @lucapette. The Google standard is text (because it always works) + buttons optionally. If we could support buttons (a.k.a. suggestions or quick replies) as well that would be great. 

If we could even render a rich card or carousel as the first message as an optional element that would be a great variation, but we could also absolutely live with text + buttons to simplify things (like on Google). 

In terms of setting the default we should value out functionality (text always works and is easy to configure) vs. user experience. It also can get tricky soon - thinking of customization around browser language, etc. as additional requirements....

**Comment by lucapette** [comment]
ok then we should split this in several features:

- Add all the "missing content types" for the chat plugin (we're talking about basically the same thing in #1004 and I think it's all based on the same confusion/assumption that the chat plugin as more rendering abilities than it actually does)
- Add one feature where we make it possible for chat plugin users to bring their own payload for the welcome message

**Comment by lucapette** [comment]
then I'll close :)
