### ISSUE TITLE
Expired Websocket Connection

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#1055]
When a user writes something in the chat plugin, leaves the tab open for 1-2 hours (or longer), and then writes another message after that time has elapsed: their most recent message is unable to send.

One reason for this may be that the websocket connection expires.

We need to detect when this happens and find a strategy to either re-activate it or close it.

**Comment by chrismatix** [comment]
@lizhutter currently the expiry time of the authentication token on the chat plugin is set to 1 hour. We could increase that time, but it doesn't solve the problem you mentioned of course:

If you can re-activate an expired token then there's no point in expiring it in the first place, so I'd perhaps argue that if the token is expired the chat plugin either:
1. Does a complete reset.
2. Disables the chat and displays a refresh button that uses the [resume token](https://github.com/airyhq/airy/issues/527) which we added.

**Comment by bitboxer** [comment]
So I think I could do a reconnect when the websocket disconnects and then if that fails, show an "restart connection" or I could just refresh it. I think the refresh is better for the user experience because the users will not be afraid of loosing messages. But if the backend has a relatively low limit of possible websocket connections, we should go with the "show the user a message" approach.

**Comment by chrismatix** [comment]
@bitboxer Websocket connections should not be a limiting factor. We could make that part work for sure 🙌 

I would agree with the re-connect idea, but my question would be: How do you re-connect? You would have to use the `resume_token` because the actual authentication token is expired. But the idea behind the resume token was that you could use it to prompt the user to resume conversations using links or something else that requires user interaction. Otherwise, we could have just turned this into a refresh token.

**Comment by bitboxer** [comment]
The code already is using it as a `refresh token`. If you close the tab and open it up again, it uses that token to get the last conversation state without clicking anything besides opening up the airy chat box. If what you saying is true, this behavior is wrong 😟

**Comment by chrismatix** [comment]
@bitboxer Yeah I just checked and was pretty surprised to see that we store the resume token 😅 It's the same as setting a week-long expiry on the auth token and adding a "get messages" endpoint. Neither of which is great (it's certainly a big security risk), but if it's wrong depends on what the goals of the resume process are. Maybe @lizhutter can share more on that.

**Comment by lizhutter** [comment]
@chrismatix Best case scenario, we'd like to re-activate automatically. If this is not possible, we'd want to close the conversation in a way that displays a state/message letting the contact know that the conversation is over (something maybe along the lines of "click here to resume").

**Comment by chrismatix** [comment]
@bitboxer Ok to unblock this I think it's fine if we go for your solution and simply use the resume token to also refresh conversations. 

I think long-term we need to find a more secure mechanism for dealing with token refreshing, because as I said the resume token grants you an auth token and the full chat history, but it is valid for seven days.
