### ISSUE TITLE
Receive Resume Token for Chat Plugin via the Webhook

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#1097]
As a developer consuming events from the webhook,
having an Airy chat plugin running on one of my websites at the same time,
whenever an end user is in a conversation via the chat plugin on my website,
then I want to receive a resume token via the webhook together with incoming messages,
so that I can send the end user a notification (e.g. via SMS or email) including the resume token,
so that the relevant end user can continue the conversation 
(i.e. without relying on a cookie being there in the browser on the device that started the conversation)

Alternative solution: 

If you don't want to broadcast such resume token via the webhook for security reasons, please provide a secure route instead that I could use to query with an authenticated request for a resume token to represent a participant for a relevant conversation_id.

Additional requirement:

Some kind of documentation on how to use the resume token with the chat plugin (how to inject it via the url, etc.) so that we can lead the relevant end user back to the conversation.

**Comment by chrismatix** [comment]
@steffh If we would send the resume token via the webhook the conversation metadata seems like the best fit. However as you pointed out this is a strange behavior so I would indeed suggest that we add an endpoint that allows fetching resume tokens for a user. 

However I'd suggest that we complete [this ticket](https://github.com/airyhq/airy/issues/1036) first so that you can do these things with an API key.

**Comment by steffh** [comment]
@chrismatix - yes that makes sense!

**Comment by lucapette** [comment]
Moved to ready as there's seems to be an agreement on how to solve the problem. We will expose an endpoint for this purpose (as it's true that the webhook integration seems an odd place for this). 

I added the label waiting as it makes sense to wait for #1036
