### ISSUE TITLE
Use Minikube registry to test images locally

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#1246]
**Current State**

A common issue we face when developing features is testing images in integration with the core installation. In #1041 we introduce `minikube` as a new local provider. 

**Idea** We could use the local image registry minikube provides to test and reload changes without the need of pushing image tags to GitHub.

In the context of this issue, we also want to document the dev workflow. Idea: add a new document in the `concepts` section of the docs and link it back from the contributing.md. The doc should mention:

- how to run airy create for minikube
- set up the local registry
- create a cluster from a branch
- run all the cypress tests as well

**Comment by lucapette** [comment]
Waiting for #1041 to be there

**Comment by chrismatix** [comment]
In the latest version of minikube it's now also possible to use [image load](https://minikube.sigs.k8s.io/docs/commands/image/#minikube-image-load) to import local images directly into the cluster.

**Comment by lucile-airy** [comment]
Pushing images to minikube's docker registry with bazel is not possible without having the necessary certificates and setting environment variables `DOCKER_TLS_VERIFY`, `DOCKER_HOST`, `DOCKER_CERT_PATH` and `MINIKUBE_ACTIVE_DOCKERD`.
Doing this in bazel would be nontrivial and unstable, but there is an easy workaround that we could add to the docs.

If you want to build and test/release your images on a local Airy Core instance with minikube, you first have to point your current docker to minikube's docker registry by
```
eval $(minikube -p airy-core docker-env) 
```
You can test if this worked by simply running `docker ps` which should show you all containers currently running on Airy Core.

If you run a bazel target with `:image`, bazel will generate an image locally and push to this docker registry. Example:
```
bazel run //backend/api/communication:image
```
You can test if this worked by running `docker images` which lists all images, including the newly built 'bazel/backend/api/communication:image'.

To run this in the cluster, you should modify the deployment's image name and also set `imagePullPolicy: [IfNotPresent|Never]` for this deployment.

Perhaps it's also a good idea to include a new bazel rule that will publish the local image with tag `:latest` since otherwise further updates to the image will be ignored by minikube.

**Comment by chrismatix** [comment]
@lucile-airy makes sense. Why should we set the image pull policy to `Never`?

**Comment by lucile-airy** [comment]
@chrismatix I think that is generally undesirable but someone can do this if they want to run their whole Airy Core from local images I guess.
The main point is that it should not be `Always` :)

**Comment by chrismatix** [comment]
@lucile-airy I see. It depends a bit on how we want to handle _subsequent updates_ to images. If we set the deployment's image tag to `backend/api/communication:image` then we would have to use `Always`, because the image tag does not change.

**Comment by lucile-airy** [comment]
@chrismatix I have found that the problem is if we use `Always`, kubernetes will look for the image remotely and not consider local images. It gives me this error message: `Failed to pull image "bazel/backend/api/communication:image": rpc error: code = Unknown desc = Error response from daemon: pull access denied for bazel/backend/api/communication, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`
 That is why I suggested changing the tag to `:latest`.

**Comment by ljupcovangelski** [comment]
I tested and it works perfectly @lucile-airy. 

What I did:
```
airy create --provider minikube
eval $(minikube -p airy-core docker-env)
bazel run //backend/api/communication:image
kubectl patch deployment api-communication -p '{"spec":{"template":{"spec":{"containers":[{"name":"app","image":"bazel/backend/api/communication:image","imagePullPolicy":"Never"}]}}}}'
```
It seams very easy to do :tada:
