### ISSUE TITLE
Introduce a helm_test rule

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#1279]
There is currently no validation for the Airy Core helm charts in `infrastructure/helm-chart`. Often they get bundled in the container and the helm templating syntax, which is prone to errors, crashes at runtime

**Proposal**

Add a Bazel test rule `helm_test` that runs [helm template](https://helm.sh/docs/helm/helm_template/) on the directory to see if there are any syntax errors _given the default configuration

```python
load("//tools/test:helm_test.bzl", "helm_test")

helm_test(
    values = "values.yaml",
    srcs = ["Chart.yaml"] + glob(["charts/**/*", "templates/**/*"])
)
```

**Comment by paulodiniz** [comment]
I like that! Big 👍

**Comment by pascal-airy** [comment]
I haven't figured it all out but I think we can use this [rule](https://github.com/masmovil/bazel-rules#helm_chart) to test and build the helm package. Furthermore, we could then even get rid of the `upload-helm-chart.sh` and use the release target of said rule.
We do then also need a [Helm Chart Repository](https://chartmuseum.com/) but I think the effort is worth it because the whole process of managing our Helm package becomes more standardized.
