### ISSUE TITLE
Thanks for update-deps

### ISSUE THREAD

**Issue by ajbouh** [airyhq/airy#1409]
This tool was hugely helpful for getting my go_repository rules under control. Thank you!

I made some changes to get it to behave for me:

1. Switched from `go get .` to `go mod download`
  Using `go get .` failed with `go get .: no package in current directory`, but `go mod download` seemed to work.

2. Switched `filepath.Walk` to `filepath.WalkDir`. This was optional but probably worth it since we don't need the `FileInfo`.

3. Skipping directories whose `go.mod` files I *never* want.
  ```go
func FindSourceModules(rootPath string) []string {
	paths := make([]string, 0)

	skip := func(path string) bool {
		switch filepath.Base(path) {
		case ".git":
		case "node_modules":
		case "pkg":
		case "vendor":
		default:
			return false
		}

		return true
	}

	err := filepath.WalkDir(rootPath, func(path string, d fs.DirEntry, err error) error {
		if skip(path) {
			return fs.SkipDir
		}
                 // ...
```

Hope these changes are helpful to you and/or others

**Comment by chrismatix** [comment]
Thank you so much for this feedback @ajbouh. Glad that you could get some use out of this tool! 

I have integrated 2. and 3. in #1428, which is why I am closing this issue for now. I also updated the tool's README to point out that to make this work with `go get` one has to add an (empty) `main.go` to the repository's root, because it requires a go package to be present. We prefer `go get` since it ensures that the project is `go build` compatible.

Note to people coming across this issue: The tool will be moved to https://github.com/airyhq/bazel-tools in [this ticket(https://github.com/airyhq/bazel-tools/issues/33). This way you can install it directly as a dependency rather than copying the directory.
