### ISSUE TITLE
airy create doesn't use passed config dir

### ISSUE THREAD

**Issue by pascal-airy** [airyhq/airy#1638]
Current
airy cli version 0.18.0

<img width="712" alt="Screenshot 2021-04-26 at 11 48 39" src="https://user-images.githubusercontent.com/54705263/116068160-3633e380-a68a-11eb-8852-9ec4114803a7.png">

Desired

`airy create` should abide to passed `--config-dir`

**Comment by thorstenairy** [comment]
<img width="874" alt="Screenshot 2021-04-28 at 15 51 19" src="https://user-images.githubusercontent.com/49147864/116415415-b0569a80-a839-11eb-81a4-3f438766636e.png">

**Comment by chrismatix** [comment]
@pascal-airy @ljupcovangelski  This is by design. The `config-dir` is passed in as a positional argument and not as a flag. In fact, I'd argue for removing the flag since it's not clear how the command should behave if the user passes both the flag and the positional argument.

**Comment by lucapette** [comment]
`airy create project-name` is the idea of the UI (ala `rails new website`) so in that sense it's not really a config dir but more a workspace (as @chrismatix has suggested/implemented it in the code of the CLI itself) 

As I see it, the problem is that we look at the UI of these commands differently. It's either a workspace and then `airy create my-project` is the "right UI" or it's not a workspace and we should do a full review of the UI (I say that because if it is indeed a workspace then we only need to fix `airy create` to support the workspace name)

**Comment by pascal-airy** [comment]
Works fine now 👍
