### ISSUE TITLE
Binary successfully installs on Windows but paths are different on Mac and Linux

### ISSUE THREAD

**Issue by Decmcc** [airyhq/airy#1951]
![image](https://user-images.githubusercontent.com/54137451/121326148-302c5600-c90a-11eb-8921-877df52b8e4c.png)

**Comment by ljupcovangelski** [comment]
Hi @Decmcc, thanks for submitting the issue. I think the problem here is that in order to run `airy ui` and access the web user interface, you need to successfully run `airy create` first and create a workspace directory. 

You probably know, but just a note that `airy create` currently has a [bug on Windows](https://github.com/airyhq/airy/issues/1952)  and we are working to solve it.

**Comment by chrismatix** [comment]
Closing this as it's not an actual bug in our system
