### ISSUE TITLE
Facebook Source: Process Typing Indicator Events via Websocket

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#2122]
We should process typing indicator events so relevant conversational interfaces such as our Airy Inbox UI are able to indicate to logged in users that the relevant contact is still typing.

The sender actions message property allows you to control indicators for typing and read receipts in the conversation via the `Send API`. This is helpful for letting message recipients known you have seen and are processing their message.

To display a sender action in the conversation, send a `POST` request to the Messenger Platform with the `sender_action` property:

```
curl -X POST -H "Content-Type: application/json" -d '{
  "recipient":{
    "id":"<PSID>"
  },
  "sender_action":"typing_on"
}' "https://graph.facebook.com/v2.6/me/messages?access_token=<PAGE_ACCESS_TOKEN>"
```

**Note**: the request should only include `sender_action` and the `recipient` object. All other Send API properties, such as text and templates, should be sent in a separate request.

### Supported Sender Actions
The following sender actions are supported. Typing indicators are automatically turned off after 20 seconds, or when the bot sends a message.

### Sender Action + Description
`typing_on`: Turn typing indicators on
`typing_off`: Turn typing indicators off

Source: https://developers.facebook.com/docs/messenger-platform/send-messages/sender-actions/

We should process and send them via the web socket but not via the webhook to avoid noise as mostly synchronous clients benefit from such real time events (compare with Slack RTM API vs. Slack Events API).

**Comment by chrismatix** [comment]
One more thing that I just noticed. Looking at the Facebook documentation it seems like the `sender_action` is a one-way road: I can't find an example for the type of payload received in the webhook.

Unless I am missing something it looks like you are only able to let Facebook know that you are typing, but there is no indication for the contact doing so.

**Comment by steffh** [comment]
Hi @chrismatix - thank you for your suggestion and remarks. 

We would prepare a separate ticket then to specify a new feature that lets people decide which events they subscribe for via the webhook. For some features like typing indicators it doesn't seem to make much sense to me that people want to receive them at all via webhooks, but if the additional effort is minimal let's rather stay agnostic and not opinionated about such things.

Regarding your suggestion for the payload - I would agree with sending a timestamp so letting the clients decide whether to still display sth or not.

@lizhutter's comment above goes beyond the initial scope of this ticket from my perspective which was ingesting typing events from a third party platform like Facebook (the contact is typing), but she actually has a fair point pointing to typing indicators for the opposite direction (the agent typing in one of our apps) to be relayed back to the relevant third party platform. However, for this we would require another endpoint in my perspective that our apps could call when the user is typing.

From the perspective of the event to be delivered via the websocket, it would be helpful to know who is typing and not automatically assume it can only be the contact.

Looking at our existing docs here: https://airy.co/docs/core/api/websocket#metadata

For a conversation where the contact is typing I assume this could like as follows:

```
{
  "type": "metadata",
  "payload": {
    "subject": "conversation",
    "identifier": "conversation id",
    "metadata": {
      "contact": {
        "displayName": "Grace"
      },
      "typed_at": "TIMESTAMP"
    }
  }
}
```

Or would you rather suggest to move the `typed_at` property into the contact object in that case?

Also from the perspective of the clients it might be really hard to screen the payload object for keys to determine whether `typed_at` is defined or not. Looking at the way you implemented tags and channel updates having their own types as documented here (https://airy.co/docs/core/api/websocket#channel) it might justify having a separate event type instead of just sending a metadata event?

Looking again at the corresponding Slack event here (https://api.slack.com/events/user_typing), we could do sth like:

```
{
"type": "user_typing",
"payload": {
   "conversation_id": "SOME_ID",
   "user_id": "SOME_ID", // or remove because we don't have user_ids
   "from_contact": BOOL,
   "typed_at": "TIMESTAMP"
} 
```

Not sure what you think about this, happy to discuss. (I also know we don't have user_ids at the moment)

**Comment by chrismatix** [comment]
Thanks for your reply @steffh! I am addressing both issues separately:

## Sending typing indicators to Facebook
> @lizhutter's comment above goes beyond the initial scope of this ticket from my perspective which was ingesting typing events from a third party platform like Facebook (the contact is typing), but she actually has a fair point pointing to typing indicators for the opposite direction (the agent typing in one of our apps) to be relayed back to the relevant third party platform. However, for this we would require another endpoint in my perspective that our apps could call when the user is typing.

It seems like going the opposite direction (to source) is the only thing that's possible with Facebook right now. In any case: Both typing indicator tickets need to be split/edited to reflect in which way the data should flow.

## Processing typing indicators on the websocket/webhook

> In case the agent was typing, the contact would not be present in payload.metadata, but maybe that's rather weak and puts more pressure on the clients. Or would you rather suggest to move the typed_at property into the contact object in that case?

The entire metadata object is always present. And yes, putting `typed_at` on the contact field makes sense 👍 

> Also from the perspective of the clients it might be really hard to screen the payload object for keys to determine whether typed_at is defined or not. Looking at the way you implemented tags and channel updates having their own types as documented here (https://airy.co/docs/core/api/websocket#channel) it might justify having a separate event type instead of just sending a metadata event?

**Introducing a separate event**
In our taxonomy conversation metadata is any **optional** data associated with a conversation. That's not true for tags and channels, which is why we made them separate entities. Therefore I would not introduce a separate entity for that

**Clients' ease of parsing**
In Javascript languages, this is fairly easy to do, but I see how this can become cumbersome at some point. There are ways of making this look and behave a bit more like the Google `userStatus` webhook event, but I would discuss and plan them once we get there.

**Comment by steffh** [comment]
I think you are right @chrismatix - Facebook is a one way street only at this point and we don't receive typing events from the source, so I would suggest to close this ticket as this was the initial motivation for the feature.

I think your comment is very relevant, but we should continue the discussion for a source for which we actually receive these events. => https://github.com/airyhq/airy/issues/2118

**Comment by chrismatix** [comment]
That's a good idea. Hereby closing this.
