### ISSUE TITLE
Improve the Airy upgrade process

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2243]
**Is your feature request related to a problem? Please describe.**

As an Airy Open Source user I want to be able to upgrade my Airy instance to a new version.

At the moment this is accomplished by running several commands sequentially and amending config files manually.

**Describe the solution you'd like**

A CLI command such as `airy upgrade` would be nice to run instead of individual commands.

The upgrade process also should be more visibly documented in the Airy docs.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ljupcovangelski** [comment]
So if I understand correctly, if somebody wants to upgrade `Airy Core` to a new version, the procedure is the following:
- You need to download new version of the CLI
- Run `airy upgrade`. You will get information if upgrade is possible for your existing `Airy Core` version or you first need to upgrade to an intermediate version.
- The command will do the upgrade and will update your `airy.yaml` file with the new version, after the upgrade completes successfully. 
- If the upgrade is not successful - you will be reverted to your previous version.

**Comment by chrismatix** [comment]
Agree with the sequence of steps.

> Do we tie the upgrade to the version which is bundled in the CLI? Let's say your CLI version is 0.30.0 and your Airy Core cluster is 0.25.0. What if you want to upgrade to 0.27.0. Should we allow airy upgrade --version 0.27.0? If the --version flag is not set - we default to the version that is in the CLI.

I would definitely tie it to the latest version of the CLI, so no `--version` flag. Anything else would be much more expensive.

> Will upgrade only concern the version change? 

Upgrades necessarily also entail changes to Kubernetes and Kafka infrastructure such as adding routes, deployments, resetting and creating topics etc. 

To do this I would propose the following: Running `airy upgrade` does not execute the upgrade immediately. Rather it returns a command that can be run with `$(airy upgrade)`. Pseudo behavior:

```bash
$ airy upgrade
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/airyhq/airy/scripts/upgrades/0.27.0/run.sh)"
```

Benefits:
- We can fix migration scripts after releases by pushing to the cdn URL 
- We can leverage bash scripts for our upgrades the way we have been doing it in cloud

**Comment by ljupcovangelski** [comment]
> Upgrades necessarily also entail changes to Kubernetes and Kafka infrastructure such as adding routes, deployments, resetting and creating topics etc.
> 
> To do this I would propose the following: Running `airy upgrade` does not execute the upgrade immediately. Rather it returns a command that can be run with `$(airy upgrade)`. Pseudo behavior:
> 
> ```shell
> $ airy upgrade
> $ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/airyhq/airy/scripts/upgrades/0.27.0/run.sh)"
> ```
> 
> Benefits:
> 
>     * We can fix migration scripts after releases by pushing to the cdn URL
> 
>     * We can leverage bash scripts for our upgrades the way we have been doing it in cloud

I would really like to try to avoid running any extra scripts and I think we should try to build it in a way that we package these migration scripts into helm charts/jobs that run on a certain `hook`. So the script is instead run from a container inside the cluster (which also is easier because of access to Kafka and the other services) and if the job finishes successfully - then we move on with the upgrade.

**Comment by ljupcovangelski** [comment]
So, to summarize on the specs of the `airy upgrade` command:

When one runs `airy upgrade`:
- We print a report what is the current version and to which version will we perform the upgrade. We ask for from the users to confirm. We can also put a flag `--approve` so that the prompt is not needed.
- We copy the latest `airy.yaml` file in the `airy-config-map` ConfigMap.
- We run `helm upgrade` with the new ConifgMap mounted to retrieve the helm values. We overwrite the version with the `--set appImageTag` argument. For facilitating the migration scripts (when to be invoked), we can also set `--set migration=true` parameter and `--set previousAppImageTag`, so that we know that we are upgrding and from which version.
- We deploy `pre-install` hooks with migration scripts, that run from jobs inside the cluster. In the scripts we scale down, reset-apps or deploy some other data-migration-apps.
- If the migration jobs finish successfully and after that `helm upgrade` finishes successfully - we can confirm that the upgrade was successful.
- After the upgrade is done, we write the new version in the `airy.yaml` file, inside the workspace directory.
- We copy the latest `airy.yaml` once again to the `airy-config-map`, so that they are in Sync.

Proposed usage:
```
$ airy upgrade --auto
CLI version: 0.28.0
Current Airy Core version: 0.27.1
New Airy Core version: 0.28.0

Running migration scripts ..... done
Running Airy Core upgrade .......... done
Updating airy.yaml file . done

Your Airy Core was successfully upgraded
```

We can also put in the `--version` flag (defaults to the version of the CLI if it is not set), but I recommend that for now we keep it hidden (outside of the docs), so that we test a little and we make sure that doesn't cause any strange/unwanted behavior.

**Comment by steffh** [comment]
looks great to me! thank you @ljupcovangelski & @chrismatix

**Comment by ljupcovangelski** [comment]
Done.
