### ISSUE TITLE
Custom sources: Multiple Webhooks and filtering

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#2275]
**Is your feature request related to a problem? Please describe.**
In order to build custom sources, the webhook feature needs more capabilities.

**Describe the solution you'd like**

- [ ] Allow for multiple webhooks
- [ ] Each webhook can optionally provide a list of events to subscribe to. If no list is provided, all events are sent
- [ ] Add optional hmac verification to sent payloads

**Events**

Example `POST /webhooks.subscribe`
```json5
{
  "name": "Salesforce connector", // unique
  "url": "https://my-url-to-be-hit",
  "headers": {
    "X-Custom-Header": "custom-code-for-header"
  },
  "events": [
    "message:new",
    "message:update",
    "conversation:update",
    "channel:update",
    "metadata:item",
    "metadata:final"
  ]
}
```

- `message:new` Only receive new messages without metadata
- `message:update` Receive message including metadata
- `conversation:update` Receive the aggregated view of a conversation
- `channel:connect` Receive channel updates (metadata and connection state)

Since our metadata objects are split into key-value pairs you can choose to receive either every single KV pair update (`metadata:item`) or the finalized view (`metadata:final`). E.g.:

Events for `metadata:item`:

Event A:

```json
{
  "type": "metadata:item",
  "payload": {
      "subject": "conversation|channel|message",
      "identifier": "conversation/channel/message id",
      "metadata": {
        "contact": {
          "displayName": "Grace"
        }
      }
  }
}
```

Event B:

```json
{
  "type": "metadata:item",
  "payload": {
      "subject": "conversation|channel|message",
      "identifier": "conversation/channel/message id",
      "metadata": {
        "contact": {
          "lang": "en"
        }
      }
  }
}
```

versus for `metadata:final`:

```json
{
  "type": "metadata:item",
  "payload": {
      "subject": "conversation|channel|message",
      "identifier": "conversation/channel/message id",
      "metadata": {
        "contact": {
          "displayName": "Grace",
          "lang": "en"
        }
      }
  }
}
```

It's possible for `metadata:final` to emit two updates in this case if there is a bit of time between Event A and B. But every single update will consist of the full and current state of the metadata given a subject-identifier pair.

**Comment by steffh** [comment]
@chrismatix - Thank you for the suggestions. I think enabling multiple webhooks is super critical to support running several integrations in parallel.

I would like to raise a few related topics so we can clarify them upfront:

1. How would the integrations (e.g. Salesforce Connector) authenticate vis-à-vis the API? According to your proposed design I assume we would have to store the `systemToken` set in the `airy.yaml` configuration file in all relevant integrations.

An alternative design could be to create "Airy Apps" on the first level that could be granted certain permissions only (as soon as we differentiate permissions), so that tokens issued from these apps are limited to the permissions granted to the app and in case such token was ever exposed, only the relevant app would be compromised and a new token could be generated, so that it would have to only been replaced in one place instead of all remotely places where it is being stored.

The webhook to be configured and the relevant events to be subscribed could be managed as well on the level of this app with a restriction of having one webhook per app. This would also allow that we can much easier control that someone is not able to point two webhooks e.g. to the standard Salesforce Connector at the same time by accident because we can limit standard apps to be authorized only once per instance (instead of just making the name of the webhook unique as suggested).

We could offer a centralized "app marketplace" or `/destinations` folder in the repo with standard connectors that people could install their apps from, e.g. making sure that a specific connector can only be used once per instance.

2. For the naming of the events I would suggest to use more descriptive names in the past tense with underscores (which seems to be the dominant naming convention as far as I am aware, but one can also find dots as separators or camelCase occasionally):

- `message_created` or rather `message_sent` (corresponding to the `/messages.send` route) or just keep `message`
- `message_updated`
- `conversation_updated`
- `channel_connected`, `channel_updated`, `channel_deleted`
- `tag_created`, etc.

As for `metadata` can't we maybe reduce some complexity if we just do `metadata_updated` (corresponding to your `metadata:item` event)? I see very little value in consuming `metadata:final` because I would rather consume the relevant object that metadata is referring to (e.g. `conversation_updated` when the metadata of a conversation changes). In case I want to consume metadata separately, the item that changed would be enough for me when I can get the final state from the `conversation_updated`. If I need to consume metadata separately from the object, I would rather focus on need the information that actually changed.

**Comment by chrismatix** [comment]
> a) How would the integrations (e.g. Salesforce Connector) authenticate vis-à-vis the API? According to your proposed design I assume we would have to store the systemToken set in the airy.yaml configuration file in all relevant integrations.

That's addressed in [this](https://github.com/airyhq/airy/issues/2274) ticket separately. Basically, the source API can issue JWT scoped only to its use cases using standard authentication methods. So this is similar to the token approach that you suggested.

> The webhook to be configured and the relevant events to be subscribed could be managed as well on the level of this app with a restriction of having one webhook per app. This would also allow that we can much easier control that someone is not able to point two webhooks e.g. to the standard Salesforce Connector at the same time by accident because we can limit standard apps to be authorized only once per instance (instead of just making the name of the webhook unique as suggested).

I am not sure that this would solve the problems you are describing. The source API first and foremost is an API so there is no restriction on how many apps of what type you can and cannot run. 

With this design, a source/connector/app consists of an outbound channel (webhook) and an inbound channel ([source API](https://github.com/airyhq/airy/issues/2274)) that you authenticate against using an app API key. Then the app marketplace merely becomes an installation manager tasked with managing these entities. But that's out of the scope of the milestone.

> b) For the naming of the events I would suggest to use more descriptive names in the past tense with underscores (which seems to be the dominant naming convention as far as I am aware, but one can also find dots as separators or camelCase occasionally):

I am in favor of the past tense! We already use the colon as a namespace separator in other places, plus it allows us to do compound words like `customer_message:created` while separating them from the property.

**Comment by steffh** [comment]
@chrismatix: Thank you for sharing the other ticket (https://github.com/airyhq/airy/issues/2274) - I don't quite fully understand yet the entire logic, especially as you seem to generalize sources and "destinations" with the suggested approach which seems to be quite clever. So I see that you thought of the authentication topic already in that regard.

Yes, I agree. The app marketplace is out of the scope of the milestone, I just wanted us to pick a design that leaves the door open for this.

I have seen the colon widely being used in a permission context (e.g. `messages:write`), but never actually saw it for event naming. Can you think of an example for another service or open source project that does this in the way you suggested?  I have seen dots widely used for this (e.g. Stripe events - https://stripe.com/docs/api/events/types - `customer.subscription.pending_update_applied`), but never colons. Fair point regarding compound words, but this would work equally well such as with `admin_user.created`.

Regarding the point you mentioned about how the clients currently consume metadata - wouldn't they just start consuming the object related update anyways moving forward e.g. `conversation.updated` that includes the main payload + metadata? So in case metadata was updated a `conversation.updated` event would be sent including the entire payload + entire metadata? In case I understood this correctly isn't this equivalent to the current approach except providing for more granularity and also sending the main payload with it (which the clients could simply ignore). I am not sure it would be that useful to consume metadata only, except in case I just want to know which properties changed.

Or would you rather want to include in a `metadata.upated` event the entire metadata of the corresponding instead of just the metadata that was actually updated?

**Comment by steffh** [comment]
@chrismatix - thank you for the additional explanations & all good from my end!
