### ISSUE TITLE
Contacts service endpoints

### ISSUE THREAD

**Issue by juan-sebastian** [airyhq/airy#2693]
Implement the following HTTP API Endpoints:

* POST `/contacts.import`: Imports an Array of contact objects, e.g. names and phone numbers
* ~~POST `/contacts.refetch`: source-specific, for a list of contact ids, refetch the contact information from the original source, e.g. Facebook~~

* POST `/contacts.merge`: target contact_id and array of contact ids to be "merged" into target contact_id, by adding the relevant conversation in the conversations property to target and hiding the formerly separate contact_ids; when a formerly separate contact_id is queried, e.g. from a conversation, the information

* POST `/contacts.delete`: contacts without a conversation should be deletable, otherwise only if the relevant conversation was archived or "removed" first

This is the continuation of the following discussion #2293

**Comment by steffh** [comment]
@juan-sebastian
This request comes from the early days of the ticket when it wasn't clear how you would implement it, so I apologize for any ambiguity in that regard.

You are right in regards to sources that `push` contact information such as Google Business Messages, i.e. there is contextual contact information attached to every message, so the client can decide to update the relevant contact via `POST /contacts.update` or not in case there is new information received that differs from the information stored in the contact payload.

The request was in regards to sources that follow a `pull` approach such as Facebook Messenger or Instagram, i.e. the contact details are not sent with each message, but the backend does an asynchronous lookup call to the User Profile API using the `psid` of the relevant user to fetch profile information such as name or profile pic url. At the moment the backend only does this once, so not regularly and there is no way to manually trigger a refetch of failed User Profile API syncs.

At the time of writing the specification, exposing Facebook page tokens via the Channels API (https://github.com/airyhq/airy/issues/2622) had not been requested and built yet which is now available, so technically you are right. The client could refetch the user profile for these `pull` sources using the Facebook Page token and just use `POST /contacts.update` to make the changes.

The question is just how convenient this is because the client would have to know how to call the Facebook User Profile API or whether we want to bundle this functionality via the backend in a separate route such as `POST /contacts.refetch` that should also take an information for which channel you want to fetch it from and update the relevant contacts properties. But happy to discuss this, I can see why you would like to not build it this way.

**Comment by steffh** [comment]
@juan-sebastian - sorry for the slow response. I also have to apologize for the incomplete requirement for `POST /contacts.merge` here as this is from a long time ago when it was much more unclear how to even build the feature in the first place.

The core requirement here is to separate contacts from conversations so that we can have an array of conversations for a single contact, e.g. to reflect that someone is the same person on different channels.

Because we automatically create contacts per default for new conversations, pointing to the relevant new conversation, we will not automatically "merge" new contacts at this point based on rules into existing contacts, but only manually. This might already be an edge case because it is sth we rarely see in the data that the same physical person is talking to an instance via different channels.

Your example focusses a lot on how to merge payloads of different contact objects in one new contact object and according to which rules to resolve potential merging conflicts.

The idea of the requirement was to not do that at all, but just to "link and hide" one or more contact ids to a target contact_id so in this case it is more like the aggregation you described and to remove the linked contacts or `sub contacts` e.g. from the result of `POST /contacts.list`.

In terms of the payload to serve for merged contacts, we could extend it as you suggested instead of "merge" it in case that was not too costly from your perspective? Then let the client decide what to render in case a value was empty for the main contact but set for a sub contact or even to suggest changing a property in the main contact based on a value from the sub contact.

**Comment by juan-sebastian** [comment]
So after the discussion we had today. We are going to move the `contacts.refetch` endpoint to the conversation level `conversations.refetch` see issue #2745 

And for the `contacts.merge` we decided that a aggregation approach will be the way to go.

**Comment by chrismatix** [comment]
@juan-sebastian I thought we had settled on merge and delete instead of aggregation? Unless that's what you meant of course :)

**Comment by juan-sebastian** [comment]
@chrismatix What we decided is the approach of having a `key` called for example `sub_contacts` inside the contact blob so the information is always available to the user. example

We have source contact
```json
{
  "display_name": "source display name",
  "address": "source address"
}
```

and destination contact
```json
{
  "display_name": "dest display name",
  "title": "dest title"
}
```

the result of this merge will produce this:
```json
{
  "display_name": "dest display name",
  "title": "dest title",
   "address": "source address"
   "sub_contacts": [
      {
          "display_name": "source display name",
          "address": "source address"
      }
   ]
}
```

after the merge source contact will be deleted.

This is what I understand from our conversation.

**Comment by chrismatix** [comment]
All good, that's what I also understood 👍 Thanks!
