### ISSUE TITLE
Package all the components in individual helm charts

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3208]

**Comment by ljupcovangelski** [comment]
Once we have Airy installed the `airy-controller` is already there and we can use it to install the appropriate Kubernetes resources, for the particular component.

I propose a generic helm chart for a component (one chart instead of every component having its own chart). We can call this chart `airy-component`. Then, assuming that every component has it's own YAML description, we can use that file to deploy the individual component.

For example, for `api-communication`:
```
$ cat values.yaml
component: api-communication
containerRegistry: ghcr.io/airyhq
type: api
image: api/communication
topics:
  - application.communication.messages
  - application.communication.metadata
resources:
  requests:
    cpu: 100m
    memory: 256Mi
env:
  configMap:
    - kafka-config
    - security
  variables:
    - env1:
        key: ENV_VALUE_1:
        value: value
  variablesFromCM:
   - env2:
         key: ENV_VALUE_2:
         cm: core-config
         value: envValue2
```

```
helm install airy-component-api-communication airy/airy-component --values ./values.yaml
```

For example, for `sources-facebook`:
```
$ cat values.yaml
component: sources-facebook
containerRegistry: ghcr.io/airyhq
type: connector
env:
  configMap:
    - kafka-config
    - security
connector:
  resources:
  image: sources/facebook-connector
events-router:
  resources:
  image: sources/facebook-connector
```

The values can be stored in a repository where we keep a map of our components and their default values. To facilitate people building and adding their own components to an existing `Airy Core` installation, we can introduce the concept of a repository. A repository can be a file which contains a list of the components that this repository provides. We can have separate repository for `airy-core` and separate for `airy-enterprise`. But everyone can also add his own repository/component in the future.

Adding a repository, POST to /repository.create:
```
{
  "repository": {
      "name": "airy-core",
      "url": "https://repo.core.airy.co/",
    }
}
```

An alternate way would be to add a configMap that keeps a list of repositories and their components.

So when we post to the endpoint `components.install`
```
{
  "components": [
    {
      "name": "api-communication",
      "repository": "airy-core",
      "enabled": true,

    },
    {
      "name": "sources-google",
      "repository": "airy-core",
      "enabled": true,
    },
  ]
}
```

We should be able to list all the components, with filter for a particular repository from `components.list`.

**Comment by ljupcovangelski** [comment]
Update after the meeting that we had yesterday:
- We go forward with the `repository` concept, but currently we will not build endpoints for adding a repository. It will be passed to the `airy-controller` as part of a ConfigMap (implementation detail).
- The repository will be a Github URL, including a directory under which we will need to find all the possible components.
- All components will be packaged in their own charts, instead of having a generic chart. The drawbacks of this approach will be lots of helm code repetition and that we will not have a strict guideline on how to model an `airy component`, but on the other hand it will give us much more flexibility per chart.

As part of the first action item, I will continue to deploy a use-case with a single chart-component:
- Figure out where to store the charts (Currently we keep them in Github).
- Create the endpoint that lists all charts in that repository (This would be the components.list or catalog.list).
- Start with one chart first for experimentation (I will start with the sources-chatplugin).

**Comment by ljupcovangelski** [comment]
The components that will be packaged in the main `airy-core` helm chart are:
- airy-controller
- api-admin
- api-communication
- api-websocket
- frontend-inbox
- frontend-control-center

There will be no possibility for these components to be installed, uninstalled or upgraded separately from `airy-core`.
