### ISSUE TITLE
Identify components that ship together with airy-core by default

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#3286]
As we will move towards install/uninstall components, I'd like to specify once again which components ship by default together with `airy-core`. 

In my opinion these are:
- airy-controller
- api-admin
- api-communication
- api-websocket
- frontend-inbox
- frontend-control-center

Note that this is not about mandatory components. We have [discussed that before](https://github.com/airyhq/airy/issues/2142) and can conclude that only the `api-admin` (and as of recently also the `airy-controller`) are indeed mandatory.

**Comment by M-Shorouk** [comment]
@M-Shorouk : "We also had an old ticket that was open for discussion to also "Install" Inbox as a separate component. For fact, we want to also allow the user to use Airy without the inbox.
This ticket was in the scope of Airy Admin, but now since we have the control center, we would install it and uninstall it from there...
Ticket URL: https://app.zenhub.com/workspaces/airy-61f94fc6acedfd001f39b1d0/issues/airyhq/airy/2354"

@ljupcovangelski : "We need to define which components ship by default. We can remove the Inbox from the list, it is a product decision. The more lightweight the instance, faster it will run also locally"

@ljupcovangelski : "Then we also don't need the api-websocket by default I guess? Because that is only useful if the frontend is running, right? [@team-frontends](https://airy.slack.com/admin/user_groups)?"

@AitorAlgorta : "I think the frontend is not mandatory but it should be installed by default. You should choose to disable it"

@M-Shorouk : I assume that Inbox is a regular component that the user can install or not, so it shouldn't be "defualt". If so, then we would need to remove frontend-inbox as well as api-websocket components from the "Default" installed components.

**Comment by ljupcovangelski** [comment]
@AitorAlgorta @M-Shorouk If we disable the Inbox, we would need a new/smart start page right? To check if the Inbox is enabled and display the block only then.

**Comment by AitorAlgorta** [comment]
I think we should be able to disable the inbox, but I am not sure about disabling the control center. What do you think?

**Comment by M-Shorouk** [comment]
@ljupcovangelski i assume that yes we would need a new start page which only has control center as default and also checks , after first_signup or so, if Inbox is INSTALLED & ENABLED, to be shown on this start page.  Right?

**Comment by ljupcovangelski** [comment]
I agree @M-Shorouk, that is also related to the same issue!
The reason @AitorAlgorta is that if the Inbox is disabled, then the block in the `Start page` should not be present I think..

**Comment by M-Shorouk** [comment]
@ljupcovangelski i created this ticket for this purpose, please feel free to edit the ticket. 

Link: https://app.zenhub.com/workspaces/airy-61f94fc6acedfd001f39b1d0/issues/airyhq/airy/3306

**Comment by M-Shorouk** [comment]
@ljupcovangelski @AitorAlgorta ,  I had a conv. with @steffh and we discussed the following: 

1. We shall keep Inbox enabled by default > In Installed state, not configured; no sources added. 
This flow is currently preferred to direct the user awareness to Inbox existence as ON by default. The user can uninstall Inbox from Catalog if they really don't need it. In this case, the "Smart" start page has to only show "Control Center" UI.  


2. WILL HAPPEN IN NEXT RELEASES: We will work on an onboarding flow on Control Center  in order to maintain this smart start page as default and direct the user through the onboarding flow to Install Components such as Inbox.

**Comment by M-Shorouk** [comment]
@ljupcovangelski based on our last discussion on our release planning, to move forward with this ticket, we agreed on the following: 

Mandatory component list the ship by default with Airy: 

- airy-controller
- api-admin
- api-communication
- api-websocket
- frontend-inbox
- frontend-control-center

[CAN YOU CONFIRM?] We shall refrain user from Uninstalling/disabling any of these "Mandatory" components for now.
