### ISSUE TITLE
Two Terraform environments for a single Airy Core Install 

### ISSUE THREAD

**Issue by armanjindal** [airyhq/airy#3334]
To install `Airy Core` there are two separate Terraform environments `kubernetes` and `airy-core`. 

This makes the installation more complicated as `terraform init` and `terraform apply` have to be called first in the `kuberenetes` directory and then the in `airy-core` directory. Destroy is also complicated as the reverse order has to be followed. 

When installing Airy Core with the CLI there can only be one deployment per workspace, so to have two TF environments to manage a single deployment unnecessarily complicates the management of the Airy deployment.

**Comment by armanjindal** [comment]
It seems that it is necessary for us to have two separate Terraform environments. This has to do with the way `terraform init` works, where the providers are configured **before** any resources are initialized. This is an active discussion since it is a problem other people have faced https://github.com/hashicorp/terraform/issues/2430

This is actively being worked on, (the last commit was 15 days ago). There are a few approaches here:

1. Do a hack workaround, mentioned here - https://github.com/hashicorp/terraform/issues/2430#issuecomment-370685911, where we create a resource called `kubeconfig` that uses the module outputs from the Kubernetes cluster, and then make this `depend_on` the cluster. This might have issues described [here](https://github.com/hashicorp/terraform/issues/2430#issuecomment-1054487362). 

2. Use two separate TF environments and use the scripts to install and destroy. This becomes the way users interact with the cluster. Output the `.kube.conf` file in the `terraform` file, 

```
airy /
   terraform/
      /kubernetes
      /airy-core
  airy.yaml
  install.sh
  upgrade.sh 
  destroy.sh
```

3. Explore - https://github.com/kbst/terraform-provider-kustomization/pull/186 - an external fix for this issue.

Any suggestions here for the approach?

**Comment by ljupcovangelski** [comment]
@armanjindal nice research :+1: 

I think it is better to move forward with approach `2.` because, as you already pointed out, the Kubernetes provider will not be able to plan what to change unless it can query the actual cluster (which doesn't exist before we do the first `terraform apply`).

I think that it will ge good to store the kubeconfig in the state and pass it to the kubernetes/helm provider with the `local_file` resource, so that we can delete it once we destroy the `kubernetes` state. As of the location of the kubeconfig file, our current approach was to have it as `kube.conf` in the `workspace`, but instead of that - I would move it under `airy/terraform/kubernetes`.

If the states are separate, then the logic of when to create/destroy what is on our side and we would need to make sure in the scripts that one state is successfully created/destroyed, before moving on to the other in the sequence.

**Comment by armanjindal** [comment]
After further discussion and relating it to the milestone on [decoupling the CLI from Kubernetes], the new (default) file structure for the install
```
[Airy Workspace Directory] /
   terraform/
      install.sh
      upgrade.sh 
      destroy.sh
      /airy-core
      /[PROVIDER] (default = "aws-eks"
      kubernetes.tfstate
      airy-core.tfstate 
      kube.conf
  airy.yaml
```
The reason for this file architecture is so that the `terraform` directory can be placed anywhere (not necessarily in the airy workspace directory). All the relevant files to the deployment are in this directory. 

This also allows for flexibility in installing separate environments using the future`airy install --terraform -provider` command which will install the relevant directory `[PROVIDER]`.

This new file structure is reflected in the mono repository under where a new `install` directory is created which will contain the multiple directories that will be locally installed on the installers machine, which reference the modules for the different providers in the remote `modules` directory.
