### ISSUE TITLE
Helm installation on Minikube is incorrect

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#3539]
## This is how we could improve the [documentation](https://docs.airy.co):

Did you spot an error in the docs or do you think something is missing? Write a clear and concise description of your change request.

The flow for installing Airy on Minikube using Helm is wrong:

1. The Minikube command should be with the Docker driver, instead of the Virtualbox one:

```
minikube -p airy-core start --driver=docker --cpus=3 --memory=7168 --container-runtime=containerd --ports=80:80 --extra-config=apiserver.service-nodeport-range=1-65535
```

2. The suggested `airy.yaml` file works only for cloud installation and not for Minikube. We should suggest creating the `airy.yaml` file by running the Airy CLI with `--init-only` or by suggesting the default file:

```
global:
  host: localhost
ingress-controller:
  ngrokEnabled: true
```

**Comment by bilgeAiry** [comment]
The pull request of this issue is https://github.com/airyhq/airy/pull/3566 
The with the yarn start the page did not work on the latest node version, installed the latest stable node version with nvm (v.16.13.0).
The package.json for docs requires an update. Here is an example issue:

https://github.com/facebook/create-react-app/issues/11565

package.json for docs maybe needs an option like that:
  "engines": {
    "node": "sth",
    "npm": "sth"
  },

**Comment by bilgeAiry** [comment]
I supposed to say "engines" propety of json file.. still using the wrong dialect #newinweb

**Comment by bilgeAiry** [comment]
yes we could close it -> https://github.com/airyhq/airy/pull/3566
