### ISSUE TITLE
Adding Component status reference to Connectors card view 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3668]
## Is your feature request related to a problem? Please describe.

As an Airy user on Connectors view i always see the "CONNECTOR" status as " Not configured - Enabled - Disabled". However, when the component itself is not healthy, such info is only represented on Status view, on Connectors view the connector status still refers to "Enabled". 

As a result, Airy user is still able to send a message that won't be sent as the component is not healthy giving to feedback that the component itself is not healthy. 

## Describe the solution you'd like

We need to show the bot status on the connector card to reflect the actual status of the component. In other words, regardless if the connector is "Enabled", it still can have an error as the component is "Not Healthy". 

## Describe alternatives you've considered
Suggestions?

**Comment by ljupcovangelski** [comment]
I think the component should be able to be configured even though it is not healthy (Actually changing the configuration can be a reason to make it unhealthy). In that sense, it is not that important on the `Connectors` page I think to be able to see the status (it will be duplicated information, even though enabled/disabled is already duplicted).

However, I do recommend merging the `Status` and `Connectors` pages into one (called Dashboard or Components) because:
- Components should also have the possibility to be configured (I'm not sure what is the flow to do that at the moment).
- For example on the `Status` page, we can add a "gear" icon in every line which will lead to the screen for "configuring the component"
- We can add a filter for `Connectors` on the page (if we want only the connectors to be visible on one page).
- For me this way will be much clearer and understandable, also I have the possibility to see all connectors, enable, see status and click configure on the same page.
- This way we make sure the names are unified (At the moment, the Facebook connector is `sources-facebook` on `Status` and `Facebook Messenger` on `Connectors` page).

**Comment by M-Shorouk** [comment]
@ljupcovangelski 

1. The component can still be configured when it is not healthy. On Status view, the status shown there reflects the 
Component health status. However, on Connectors view, the status shown there reflects the connector's status. Once the user is on Connectors view, currently, one only sees "connector" status not the whole component status. Which means, if the component is not healthy, you won't see anything wrong with your connector. It is true there is redundancy, we also had it in old designs and removed it, but i think its a quick solution to reflect the actual status of the connector on Connectors view. If the component is not healthy, the connector can't be healthy even if the connector itself is enabled. 

2. We can consider this gear icon, it actually sounds good, but have to scope it to the status view page as well. We are trying to make this Status view page the most informative as possible. Also we should allow the user to take fast actions from the same page e.g: Enable/disable and also could add this gear icon.

**Comment by ljupcovangelski** [comment]
Thank you for the explanation @M-Shorouk :pray: 
I understand now better. I will just note that that the health-status of the connector is the same one as the component, as the connector is a component (1:1).

It is great that the "Status" page is informative, but from a user perspective for me it takes an extra step: 1) I see that the component is not configured 2) now I need to go to the other screen where the connectors are 3) I need to click on the connector to configure it

And the "configuration" doesn't cover the components which are not connectors. We cannot configure them.
