### ISSUE TITLE
Filter conversations by metadata

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#370]
Currently `conversations.list` allows filtering on three fields. We would like to enable filtering on any conversation metadata so that we can build features that need to rely on different (authorized) views of the data.

TODO: Discuss API query syntax

**Comment by chrismatix** [comment]
We have sofar discussed two options:

1. Integrate an (embedded) query store like [Solr](https://cwiki.apache.org/confluence/display/SOLR/EmbeddedSolr) and then use the Lucene syntax.

2. Stick with the rocksdb store for now and use a document style query syntax that could look like so:
```
{
  "filters": [
    {
      "key": "conversation.channel_id",
      "value": ["123", "1234"],
      "comparison": "oneOf"
    },
    {
      "key": "source.contact.first_name",
      "value": "Grace",
      "comparison": "matchText" // regex
    },
    {
      "key": "source.contact.conversation_id",
      "value": "53b696be-ef96-48d6-87b0-79d53c324b6a \n",
      "comparison": "equals" // exact match
    }
  ]
}
```

This approach requires that we use Jackson polymorphism on the request payloads.

cc @lucapette

**Comment by lucapette** [comment]
I'd step away from the implementation for now (because, for example, you could do lucene syntax and still use rocksdb), the question to me is what's the feature set we should expose (aka what kind of filtering one can do) and what's the most developer-friendly UI we can provide.

To me the most critical point is to clarify how to combine filters together. As I understand it, in the example proposed we'd have to default to either `and` or `or` (funny word play is'nt it?). I can imagine we could expand the syntax of the proposed JSON. The obvious alternative is to provide a lucene like syntax. The JSON would look different:

```
{"filters": "conversation.channel_id: (123 1234) source.contact.first_name:\"*Grace*\" source.contact.conversation_id: \"\53b696be-ef96-48d6-87b0-79d53c324b6a\""}
```

this syntax would answer the question about boolean operators in a nice (kind of standard way).

One bonus point of using this syntax: it would be more future-proof both for us (because we could rely on a hand-made search first and then rely on a lucene server if needed) and for the users of the platform (because they could also do the same if we never end up relying on lucene). But, as I said, I'd focus on the feature set/UI first
