### ISSUE TITLE
Whatsapp connector !config error 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3885]
## Describe the bug

When installing Whatsapp Business Cloud component, on Connectors view, the connector appears to be "Not Configured' but has 1 connected channel. 

## To Reproduce

1. Install Whatsapp Business Cloud component from Catalog view. 
2. Navigate to Connectors view and find Whatsapp Business Cloud Connector.
3. See error on connector card that the status is not configured but the connector has one connected channel. 

## Expected behavior

When a user installs a new source component. it can't have any connected channels as the user needs to apply configuration first before being able to add a channel. 

## Screenshots

FIG1. WHATSAPP BUSINESS CLOUD CONNECTOR CARD ON CONNECTOR VIEW
![Screenshot 2022-10-27 at 13.11.11.png](https://images.zenhubusercontent.com/61d6c337ede24c2a3fdfa338/cc81cf8f-1ca9-47e0-8601-c9d4808ba0d4)

## Environment

- Browser: [Chrome]
- Version: [0.51.0]

**Comment by AudreyKj** [comment]
We agreed on this flow: 

---> if a component is `not configured`, we do not show the connected channels (if the component has any)
--->  if a component is  `disabled` and `unhealthy` status: do we show the connected channels (because it means that the connector is configured and you can add channels)
