### ISSUE TITLE
Populate contact information in conversation payload

### ISSUE THREAD

**Issue by AitorAlgorta** [airyhq/airy#427]
We need to populate the contact information in the conversations payload in order to display the conversation properly in the demo app. Sometimes we don't get any information about the contact from the source and we should discuss how we want to populate this.

**Comment by chrismatix** [comment]
**Backend solution proposal:**

As a default, populate `contact.first_name` with the source name, `contact.last_name` with a random number derived from the `conversation_id`. The reasoning for this is that not all sources will ever return this information, so before we start adding source metadata fetchers (upcoming), we introduce a scalable default. cc @paulodiniz @lucapette 

Addendum: Since source names can look like `twilio.sms` and `facebook` we should come up with a generalized transformation that turns them into `SMS (Twilio)` and `Facebook`.
