### ISSUE TITLE
Enable users to connect via Google Business Messages

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#661]
### Summary
To enhance overall experience, we should offer the ability to connect Google Business Messages for Google business pages.

### Requirements
On Airy Core, it should be an option to connect GBM for Google business pages. We need to clearly state that Google only allows a few partners to enable messaging. Along with this notice, we need to deliver a message including the Airy GBM documentation.

When connecting Google Business Messages, we need to request the following information:
- Agent ID
- Avatar
- Display Name

### Design Note:
Please note that although the following items are included in the above image, we will not include these:
- Welcome Message
- Add a name (optional)

For the Avatar, we need to clarify that this will be used for internal purposes only as a means of differentiating between channels. We also need to state that without a set image, it will be assigned a standard icon within Core.
![3 3 0 Connect Google @2x](https://user-images.githubusercontent.com/74183162/104713949-d8a40880-5724-11eb-8deb-b48aad814f2a.png)

Once the Agent ID has been connected, the Google business page should be visible on the Admin page, along with the avatar and Agent ID. It should be possible to see whether the page is properly connected. If it is not, we should display an error message next to the affected page.
![3 4 0 Connect GBM@2x](https://user-images.githubusercontent.com/74183162/104713953-d93c9f00-5724-11eb-971d-6c1aae42edf9.png)

**Comment by lucapette** [comment]
At the moment, we do not support any call to the gbm api to programmatically request agent ids. So I added the backend label for that reason (if we want to do this, it needs backend work. Right now `/google.connect` does not do any API call to GBM) and the "needs discussion" one so that we can sort out:

- what exact api call should we make here to fulfill the requirements
- what to do with the "welcome message". The platform does not support this feature so unless it can be done on GBM side (I don't personally know about this), we should probably take it out in the first iteration

**Comment by lizhutter** [comment]
related to #665

**Comment by AitorAlgorta** [comment]
https://airy.co/docs/core/sources/google#connecting-googles-business-messages-to-your-airy-core-instance
