### ISSUE TITLE
Stream metadata to webhook/websocket

### ISSUE THREAD

**Issue by lucapette** [airyhq/airy#863]
There's a variety of reasons why streaming metadata updates is good. It covers avatars, tags update in the UI. It allows custom apps to build more complex workflows (as they have access to more data).

What we need to figure out:

1. We introduce "event types" for the webhook (so that we can have a message type for the existing events and a new type for metadata? this would also open the door to other types like message read/typing indicator/etc)
2. Should we introduce a high level metadata queue for WebSocket and have the UI consuming the "raw metadata" and react accordingly? Or we "hide the low-level metadata" api and have "logical" queues like "contact updates" "tags updates" and so on?
3.  The way we currently expose metadata via the HTTP api is somewhat confusing:
    - we have an info field inside the contact of a conversation in `/conversations.list` (which only exposes "public" metadata)
    - the http endpoints we have now are not generic enough as they only work for conversations. So right now there's no way to add/remove metadata from other objects
    - tags are their own thing but they use the metadata api. We have to take this into account for the whole picture. For example, if we design the system so that clients get the raw metadata attached to the relevant objects, you could argue we can throw the tags endpoints away (it's a stretch maybe)

I assume there's not really another way to do `1.` which is why I stated the change more than offering a solution but, please, do correct me if there's other ways.

About `2.`, I'm not sure. On one side, the system may benefit quite a bit from a complete API symmetry between websocket and webhook (we could use one topology for example), on the other hand the UI would have to do some heavy lifting work (but there's a decent argument for "let the websocket lib do the work... so we can also share that with people" and the UI just uses the high level updates coming out of the lib.

As for `3.`, the core question to me is should we get rid of tags? (As in, we ourselves use the metadata api and the UI finds the right things based on a convention?). This argument seems weak at glance and not so important but it's been on my mind since we opened #422 for which we still don't have a good solution (and having only one metadata concept, everything else is a convention, would greatly simplify building such a feature) and the more general question is should we even make the distinction between public/tags/machine metadata?

**Comment by chrismatix** [comment]
1. I agree that there is no other way around and I think that the data model for metadata here should be the same as what we expose on `2.`

Now the central question that you raise is: **Should we expose metadata as the series of k/v updates that it is on our store <subject, identifier, object.nested.key, value> or should we build the object view for the APIs?**

**A** Exposing the k/v updates:
- Less backend code
- Better update API for clients (?)

**B** Exposing an aggregated object:
The Google Business Message context field on ingested messages is a good reference for how this could look like:
```json5
{
  "message": {
    //...
  },
  "context": {
    "entryPoint": "CONVERSATION_ENTRYPOINT",
    "placeId": "LOCATION_PLACE_ID",
    "resolvedLocale": "MATCH_OF_USER_AND_AGENT_LOCALES",
    "userInfo": {
      "displayName": "USER_NAME",
      "userDeviceLocale": "USER_LOCALE",
    },
  }
}
```

Come to think of it `context` is also a good name for metadata. In any case for us the difference is that metadata could be attached to different things, so either in the websocket or the webhook this could look like so:

```json5
{
  "subject": "conversation|message|channel",
  "id": "uuid",
  "data": {
    "contact": {
      "displayName": "Roy McBride"
    },
    "isUserTyping": false
  }
}
```

From the Google webhook we know that it's convenient to consume this data, especially since we have to maintain a schema either way. The update API could look the same and we can easily imagine how you would break down such an object into k/v updates


3. Completely agree with you on this one. No matter if we go for **A** or **B** we should make it transparent that it's simply metadata. However I am not quite sure if I understand the proposal to get rid of tags yet? Right now the metadata contains the tag id, which points to a tag. This has the advantage that transactional updates (e.g. of color or name) are independent of how many tags there are.

**Comment by paulodiniz** [comment]
1. Yes 👍 This connects very well with the `Conversation events` we discussed a couple of months ago

2.  On @chrismatix point
  IMHO we should go with a simpler API (i.e: return the K.V value instead of an aggregated object) for the reason that is simpler to change both on the backend and on the client side. This way if we see the same aggregation appearing in multiple places we can discuss what to do on that case (maybe provide a specific websocket event for that?)

3. Yes 👍  Giving some thought maybe this is a case for what I discussed on `2` -> return an aggregation of the metadata via a specific websocket event or api

**Comment by AitorAlgorta** [comment]
I understand `1.` and I also think there is no other way of doing this. 

Regarding `2.` exposing the key/value updates or aggregated objects, I will always prefer aggregated objects from the frontend point of view. But I understand that maybe it is more work for you guys, so we can talk the implications of each and then decide.

About `3.` I don't fully get why should we remove the tags endpoint, maybe I am not understanding something.

**Comment by lucapette** [comment]
ok wrapping up the meeting we had about this. Here's the action points:

- We introduce `/metadata.update` (and remove the existing endpoints). The endpoint takes a subject (conversation|message|channel) and a metadata (naming all up for discussion) and always merges
- As for the existing data model, we introduce the following changes:
   - conversations: new `metadata` field with `contact` (not the `info`) `tags`, `unread_message_count` and `user_data` (this is not a good name, more on this later) with the content of the current `contact.info` field 
   - message gets a `metadata` field
   - channel also gets a `metadata` field
- The webhook/websocket api both gets updated so that they expose the following events:
   - message
   - message_metadata
   -  conversation_metadata
   - channel (I"m not sure we should keep the current connected|disconnected distinction?)
   - channel_metadata

The last point implies that:

- We introduce a `AiryEvent`: `{"event_type": "reflects the above mentioned types", data: {}}` (naming as always up for discussion
-  The websocket server changes so that:
   - clients _subscribe_ to specific events (probably `*` is a good shortcut for all events
   - There's only one queue that uses the same `AiryEvent` model

two personal thoughts on this:

- I think the naming is off with metadata if we have a `/metadata.update` but it actually only changes a subset of the metadata fields. Two solutions I can think of: top level field is called something else and the `user_data` field is actually called `metadata` (but I can't come up with anything good or top level field is called `metadata` and the `user_data` field is called `custom` (and we make it clear in the docs that the endpoint only changes the custom stuff)
- Backend wise, I think this is our excuse to exctract `websocket-communication` from `api-communication` (not so sure about the name... I'm sure something like `api-websocket` also works)

**Comment by chrismatix** [comment]
On the personal thoughts:
- We could also simply allow writing to those fields, since what's the harm if metadata is optional to the operation of the system? We could of course document that it's good practice to put user stuff into a dedicated object.
- `api-websocket` 👍 

About the impending milestone: We should have a dedicated issue for a class inside the metadata model that implements the following methods:
```java
class X {
    public JsonNode getMetadataPayload(Iterable<Metadata> metadata); // construct JSON from metadata 
    public Iterable<Metadata> getMetadataRecords(Subject subject, JsonNode updatePayload); // construct update metadata from update json paylod
}
```
This will be quite a bit of clever (but powerful!) code so it should be treated as its own problem.

**Comment by lucapette** [comment]
>     * We could also simply allow writing to those fields, since what's the harm if metadata is optional to the operation of the system? We could of course document that it's good practice to put user stuff into a dedicated object.

While I enjoy radical ideas (and I'm sure you know :)), I feel like this would open the door to accidentally overriding fields which, in turn, would result into "bugs" reports. So, to me, it's really only a naming problem.

**Comment by paulodiniz** [comment]
Created Milestone https://github.com/airyhq/airy/milestone/20 💚
