### ISSUE TITLE
Airy Live Chat: Online Status

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#927]
### Summary
To enhance user experience with Airy Live Chat, we should provide the option to display an online (or offline) status, depending on whether it is during business hours or outside of business hours.

### Requirements

Within the Airy Live Chat plugin, we should offer system users the possibility to display a generic message when it is outside of business hours and a live agent is not available. Along with this generic message, we should be able to prompt the contact to provide their name, email, and a short message that an agent can later respond to.
![wine com offline](https://user-images.githubusercontent.com/74183162/107381423-1bbc8600-6aef-11eb-9ece-564c3aa29e89.png)

### Design Notes
These images are only for illustrative purposes - this feature does not need to be built to look identical to this.

**Comment by lucapette** [comment]
A few questions:

- is airy supposed to send emails? I don't think it should. I think a better approach here is to "capture whatever it's in the form" and send it out as conversation metadata. That way a custom app can send emails (and leave airy out of that complexity/setup/whatever way people want to send emails)
- Where would we put the config for this? In the channels section? We need some UI mockups for it if that's the solution. 
- Should the message we display part of the configuration? I think it should because most people would have opinions about the exact copy there

**Comment by lizhutter** [comment]
Good points!

- I agree that Airy should not send emails - instead, we can capture what is in the form, like you mentioned.
- We could initially put the config for this within the source code of the chat plugin.
- Following the last bullet, I think the message we display should be part of the configuration.

**Comment by lizhutter** [comment]
closed with #2008
