### ISSUE TITLE
Users Signup Security Issue when running publicly

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#939]
### Summary

Maybe it is not ideal that the sign up flow is public. If the sign up flow is public:

- unauthorized/3rd party people can create users within an account whenever and however they want if they have the account details
- members of the organization can create a duplicate account within Airy Core

We would like to design a secure flow where "secure flow" means:

- the first member of an organization can go through the sign up flow to create an account
- additional members of the organization do not follow this sign up flow -- some possibilities can include an invitation from the original member or an auth provider, but possibilities are not limited to this

**Comment by pascal-airy** [comment]
Obviously a good idea! I suggest additionally to create a default user for which the credentials should be put in the `airy.yaml` or automatically created and printed to the console after the bootstrap process finished as a "first member" approach. So we can be sure no unauthorized user has the possibility to gain access.

**Comment by steffh** [comment]
With the `airy create` flow & the AWS Provider coming up this issue becomes more pressing as `/users.signup` is public and not secured and people might start to run their Airy instance in production / on a publicly reachable server.

As a quick fix I would suggest to do the following:

- POST `/users.signup` should only accept unauthenticated requests as long as the user table in the Postgres database is empty, so the first user can create an account;
- POST`/users.signup` needs to be authenticated with a valid JWT bearer token once the user table in the Postgres database contains more than one user, so the first user is able to create further user accounts and share the credentials; otherwise returns 401 Unauthorized when called without a valid JWT

**Comment by lucapette** [comment]
if that's the concern we shouldn't have a `users.signup`. the proposed logic is very complicated and what @pascal-airy is suggesting is simpler (and definitely less error prone).

**Comment by chrismatix** [comment]
Agree with what @lucapette said. The pattern @pascal-airy suggested is common for these types of deployments and will later on also allow us to provision these instances better. First come first serve does not seem very secure either.

**Comment by lucapette** [comment]
Recap:

- `airy create` prints out credentials for a first user (which will be randomly generated I guess, but that's the open question: how do we pick up a "random email"? I think there's no "good way"?)
- we remove `users.signup` all together

**Comment by paulodiniz** [comment]
@lucapette 

- 👍 on removing `/users.signup`
- Do we really *need* to be an email? If we remove the signup endpoint we'll be treating that information almost as an `id`

**Comment by lucapette** [comment]
@paulodiniz that's fair. I think we should re-evaluate the user data model anyway at some point soon. But I would in a new issue?

I think we can proceed with this as is (@pascal-airy suggested we keep `grace@example.com` for now) and we create new issues to follow up on this.

**Comment by lizhutter** [comment]
I understand that removing `/users.signup` would take care of the security issue. However, we cannot simply remove `/users.signup` without adding another option to securely add more users to an instance. Without some kind of user management via /users.list, we will not be able to know who sends a message within an instance.

Internally, we should display which user the data is coming from. We could do this by:
- extract from the token being used to call this route which user_id called the route
- extend the message object with a sender property (examples: `sender: {user_id: 123, first_name: “liz”, … }` OR `sender_id: abc123`)

Then `/users.list` would then include `abc123 = liz`. The goal is to display in the UI who sent the message. Furthermore, this can be tied into the topics of contacts, invites, roles, permissions.

**Comment by chrismatix** [comment]
@lizhutter That's a good point. Fortunately, we already do exactly that when users send a message 🎉

So to address that issue we need to expose that as `"sender_id": "1234"` (so the latter option since adding the full user information is not available to every messaging app).

I have no strong opinion on how we could handle the creation of more users, but since the first user would be the source of authority it would make sense to me that only they can call an endpoint, say `/users.create` to start with.

**Comment by lucapette** [comment]
OK I suppose there's some misunderstanding going on here.

> However, we cannot simply remove /users.signup without adding another option to securely add more users to an instance.

This is a different problem, it was never brought up so we never discussed it. I would suggest we do that in a separate issue though as it's its own problem and needs space

>  Without some kind of user management via /users.list, we will not be able to know who sends a message within an instance.

Frankly, I don't know how else to say it: but this doesn't really make much sense? It's putting things together that have nothing to do with each other.

> Internally, we should display which user the data is coming from. We could do this by:

>    extract from the token being used to call this route which user_id called the route
>  extend the message object with a sender property (examples: sender: {user_id: 123, first_name: “liz”, … } OR sender_id: abc123)

> Then /users.list would then include abc123 = liz. The goal is to display in the UI who sent the message. Furthermore, this can be tied into the topics of contacts, invites, roles, permissions.


`The goal is to display in the UI who sent the message. Furthermore, this can be tied into the topics of contacts, invites, roles, permissions.` then we should discuss this into an issue.

this is getting very confusing because we're trying to solve multiple problems at once and we bring new questions into a conversation that was so far very specific. 

A couple of things I think this can become more productive for all the parties involved:

- We expose problems in their entirety up front. Maybe even better if that happens in a google doc where we can do a first round of questions and try to keep the noise ratio here to a reasonable level
- We don't propose solutions upfront (they're never so helpful because generally they're proposed without enough context or with a very specific use case in mind which narrows down the solution space to something that is just not good enough).

What @chrismatix said though is true and practical. But I stand by the point we're mixing things that have nothing to do with each other in the same place. As I understand it we want a "revamp user management" milestone. We definitely don't want to solve all the problems in one issue (as the output can't be better than the input and this input is very confusing...)

**Comment by chrismatix** [comment]
This issue has led to a discussion, which ended up becoming this milestone https://github.com/airyhq/airy/milestone/28
